/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ChristopheBorgers (https://sketchfab.com/ChristopheBorgers)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/war-bot-animation-8767f8dc40ac4c898da743249f46f292
title: War Bot + Animation
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function RobotAnimated(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/robotAnimated.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Armature_30"
                position={[0, 0.63, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.1}
              >
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="Robot_29" />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Material}
                    skeleton={nodes.Object_7.skeleton}
                  />
                </group>
              </group>
              <group name="Base_31">
                <mesh
                  name="Object_38"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/robotAnimated.glb");